import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface DashboardStats {
  totalMessages: number;
  totalChats: number;
  accountAge: number;
  creditsRemaining: number;
  subscriptionType: string;
  milestoneProgress?: {
    messages: { current: number; target: number; percentage: number };
    chats: { current: number; target: number; percentage: number };
    images: { current: number; target: number; percentage: number };
  };
}

export const generateDashboardPDF = (stats: DashboardStats, userName: string = 'User') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(139, 92, 246); // Primary color
  doc.text('MagVerse AI Dashboard', margin, yPosition);
  yPosition += 10;

  // Subtitle
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report for ${userName}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Generated: ${format(new Date(), 'PPpp')}`, margin, yPosition);
  yPosition += 15;

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Account Overview Section
  doc.setFontSize(16);
  doc.setTextColor(59, 130, 246);
  doc.text('Account Overview', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  
  const overviewData = [
    ['Subscription Type', stats.subscriptionType.toUpperCase()],
    ['Account Age', `${stats.accountAge} days`],
    ['Credits Remaining', stats.creditsRemaining.toString()],
  ];

  overviewData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label + ':', margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 60, yPosition);
    yPosition += 7;
  });

  yPosition += 10;

  // Activity Statistics Section
  doc.setFontSize(16);
  doc.setTextColor(59, 130, 246);
  doc.text('Activity Statistics', margin, yPosition);
  yPosition += 10;

  // Draw stat boxes
  const statBoxWidth = (pageWidth - margin * 2 - 10) / 2;
  const statBoxHeight = 30;

  // Total Messages Box
  doc.setFillColor(139, 92, 246);
  doc.roundedRect(margin, yPosition, statBoxWidth, statBoxHeight, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('Total Messages', margin + 5, yPosition + 10);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(stats.totalMessages.toString(), margin + 5, yPosition + 23);

  // Total Chats Box
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(margin + statBoxWidth + 10, yPosition, statBoxWidth, statBoxHeight, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Total Conversations', margin + statBoxWidth + 15, yPosition + 10);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(stats.totalChats.toString(), margin + statBoxWidth + 15, yPosition + 23);

  yPosition += statBoxHeight + 20;

  // Milestone Progress Section
  if (stats.milestoneProgress) {
    doc.setFontSize(16);
    doc.setTextColor(59, 130, 246);
    doc.setFont('helvetica', 'normal');
    doc.text('Milestone Progress', margin, yPosition);
    yPosition += 10;

    const milestones = [
      { label: '💬 Messages', data: stats.milestoneProgress.messages },
      { label: '🗨️ Conversations', data: stats.milestoneProgress.chats },
      { label: '🎨 Images', data: stats.milestoneProgress.images },
    ];

    milestones.forEach(milestone => {
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      doc.setFont('helvetica', 'bold');
      doc.text(milestone.label, margin, yPosition);
      
      doc.setFont('helvetica', 'normal');
      doc.text(
        `${milestone.data.current} / ${milestone.data.target}`,
        margin + 60,
        yPosition
      );

      // Progress bar
      const barWidth = 100;
      const barHeight = 6;
      const barX = margin;
      const barY = yPosition + 3;

      // Background
      doc.setFillColor(230, 230, 230);
      doc.roundedRect(barX, barY, barWidth, barHeight, 2, 2, 'F');

      // Progress
      const progressWidth = (milestone.data.percentage / 100) * barWidth;
      doc.setFillColor(139, 92, 246);
      doc.roundedRect(barX, barY, progressWidth, barHeight, 2, 2, 'F');

      yPosition += 15;
    });
  }

  // Footer
  yPosition = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = 'Generated by MagVerse AI - magverse.app';
  const footerWidth = doc.getTextWidth(footerText);
  doc.text(footerText, (pageWidth - footerWidth) / 2, yPosition);

  return doc;
};

export const downloadDashboardPDF = (stats: DashboardStats, userName: string = 'User') => {
  const doc = generateDashboardPDF(stats, userName);
  doc.save(`magverse-dashboard-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};
