import jsPDF from 'jspdf';

interface ChatMessage {
  role: string;
  model: string;
  content: string;
  timestamp: Date | string;
}

export const generateChatPDF = async (messages: ChatMessage[], chatTitle: string): Promise<Blob> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper functions
  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  const wrapText = (text: string, maxWidth: number): string[] => {
    return doc.splitTextToSize(text, maxWidth);
  };

  // Add header
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246);
  doc.text('MagVerse AI Chat', margin, yPosition);
  yPosition += 8;

  // Add subtitle
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(chatTitle, margin, yPosition);
  yPosition += 5;
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
  yPosition += 10;

  // Add separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 8;

  // Process each message
  messages.forEach((message, i) => {
    checkPageBreak(30);

    // Message header - show "You" for user, "AI Assistant" for AI (not model name)
    doc.setFontSize(11);
    if (message.role === 'user') {
      doc.setTextColor(59, 130, 246);
      doc.setFont('helvetica', 'bold');
      doc.text('You', margin, yPosition);
    } else {
      doc.setTextColor(168, 85, 247);
      doc.setFont('helvetica', 'bold');
      doc.text('AI Assistant', margin, yPosition);
    }

    // Timestamp
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont('helvetica', 'normal');
    const timestamp = new Date(message.timestamp).toLocaleTimeString();
    const timestampWidth = doc.getTextWidth(timestamp);
    doc.text(timestamp, pageWidth - margin - timestampWidth, yPosition);
    
    yPosition += 6;

    // Message content
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.setFont('helvetica', 'normal');
    
    const wrappedText = wrapText(message.content, contentWidth);
    
    wrappedText.forEach(line => {
      checkPageBreak(7);
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });

    yPosition += 8;

    // Separator line
    if (i < messages.length - 1) {
      checkPageBreak(5);
      doc.setDrawColor(230, 230, 230);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = 'Generated by MagVerse AI - magverse.app';
  const footerWidth = doc.getTextWidth(footerText);
  doc.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);

  // Return as blob
  return doc.output('blob');
};
