import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

interface ChatMessage {
  role: string;
  model: string;
  content: string;
  timestamp: Date | string;
}

export const generateChatWord = async (messages: ChatMessage[], chatTitle: string): Promise<void> => {
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // Header
        new Paragraph({
          text: "MagVerse AI Chat",
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: chatTitle,
          spacing: { after: 100 },
        }),
        new Paragraph({
          text: `Generated: ${new Date().toLocaleString()}`,
          spacing: { after: 400 },
        }),
        
        // Messages
        ...messages.flatMap(message => [
          new Paragraph({
            children: [
              new TextRun({
                text: message.role === 'user' ? 'You' : message.model || 'AI',
                bold: true,
                color: message.role === 'user' ? '3B82F6' : 'A855F7',
                size: 24,
              }),
              new TextRun({
                text: ` • ${new Date(message.timestamp).toLocaleString()}`,
                color: '999999',
                size: 18,
              }),
            ],
            spacing: { before: 200, after: 100 },
          }),
          new Paragraph({
            text: message.content,
            spacing: { after: 300 },
          }),
        ]),
        
        // Footer
        new Paragraph({
          text: "Generated by MagVerse AI - magverse.app",
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${chatTitle.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.docx`);
};
