import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface Message {
  role: string;
  model: string;
  content: string;
  timestamp: string;
}

interface RequestBody {
  messages: Message[];
  chatTitle: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('📄 PDF Generation Request');
    
    const { messages, chatTitle }: RequestBody = await req.json();

    if (!messages || messages.length === 0) {
      throw new Error('No messages provided');
    }

    console.log(`📝 Generating PDF for ${messages.length} messages`);

    // Import jsPDF from CDN
    const jsPDFModule = await import('https://esm.sh/jspdf@2.5.1');
    const jsPDF = jsPDFModule.default || jsPDFModule.jsPDF;

    // Create new PDF document
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - (margin * 2);
    let yPosition = margin;

    // Helper function to add new page if needed
    const checkPageBreak = (requiredHeight: number) => {
      if (yPosition + requiredHeight > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
        return true;
      }
      return false;
    };

    // Helper function to wrap text
    const wrapText = (text: string, maxWidth: number): string[] => {
      return doc.splitTextToSize(text, maxWidth);
    };

    // Add header
    doc.setFontSize(20);
    doc.setTextColor(59, 130, 246); // Primary blue color
    doc.text('MagVerse AI Chat', margin, yPosition);
    yPosition += 8;

    // Add subtitle
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(chatTitle, margin, yPosition);
    yPosition += 5;
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 10;

    // Add separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 8;

    // Process each message
    for (let i = 0; i < messages.length; i++) {
      const message = messages[i];
      
      checkPageBreak(30);

      // Message header (role and model)
      doc.setFontSize(11);
      if (message.role === 'user') {
        doc.setTextColor(59, 130, 246); // Blue for user
        doc.setFont('helvetica', 'bold');
        doc.text('You', margin, yPosition);
      } else {
        doc.setTextColor(168, 85, 247); // Purple for AI
        doc.setFont('helvetica', 'bold');
        doc.text(message.model || 'AI', margin, yPosition);
      }

      // Timestamp
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'normal');
      const timestamp = new Date(message.timestamp).toLocaleTimeString();
      const timestampWidth = doc.getTextWidth(timestamp);
      doc.text(timestamp, pageWidth - margin - timestampWidth, yPosition);
      
      yPosition += 6;

      // Message content
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      doc.setFont('helvetica', 'normal');
      
      const wrappedText = wrapText(message.content, contentWidth);
      
      for (const line of wrappedText) {
        checkPageBreak(7);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      }

      // Add spacing between messages
      yPosition += 8;

      // Add separator line between messages
      if (i < messages.length - 1) {
        checkPageBreak(5);
        doc.setDrawColor(230, 230, 230);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 8;
      }
    }

    // Add footer on last page
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const footerText = 'Generated by MagVerse AI - magverse.app';
    const footerWidth = doc.getTextWidth(footerText);
    doc.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);

    // Generate PDF as base64
    const pdfBase64 = doc.output('datauristring').split(',')[1];

    console.log('✅ PDF generated successfully');

    return new Response(
      JSON.stringify({ 
        pdf: pdfBase64,
        success: true 
      }),
      {
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        },
      }
    );

  } catch (error: any) {
    console.error('❌ PDF generation error:', error);
    
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Failed to generate PDF',
        success: false 
      }),
      {
        status: 500,
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        },
      }
    );
  }
});
